import os

FENCE = chr(96) * 3

def update_file(filepath, content):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content.replace('__FENCE__', FENCE))
    print(f"✅ Synchronized: {filepath}")

def main():
    print("🚀 Initiating Post-Sprint Doc Sync...\n")

    # 1. Update Sprint Board
    update_file('docs/SPRINT_BOARD.md', r"""# 🏃 Active Sprint Board

**Current Phase:** Sprint 8.4 (The Polish Update)

## ✅ Completed Sprints
- [x] **Sprint 8.1:** Virality & Polish (PROJ-20). Milestone confetti, AI task badges.
- [x] **Sprint 8.2:** Medallion Pipeline (PROJ-24). Refined circular chips + transparency automation.
- [x] **Sprint 8.3:** Content Expansion. Integrated "Women for Recovery" specialty workbook with tailored UI routing.

## 🟡 Sprint 8.4: The Polish Update (Active)
- [x] **Fix:** Workbook AI results not saving to Insights Log / UI rendering properly.
- [x] **Fix:** S21 mobile template dropdown visibility.
- [x] **Fix:** Remove distracting flashing pulse from global header icon (keep only on SOS).
- [x] **Fix:** Add white background to Nav Menu Logo.
- [ ] **Fix:** Suppress "Backup Needed" warning for Google Drive auto-sync users.
- [ ] **Feature:** Admin terminology update ("Users" -> "Friends").

## 🟡 Sprint 8.0: The Road to 5,000 (Active)
- [ ] **Admin:** Receive $50,000 funding tranche.
- [ ] **PROJ-07:** Finalize Android App Store deployment.
- [ ] **Web Infra:** Move VitePress to docs.myrecoverytoolkit.ca.
- [ ] **Web Infra:** Landing page mobile polish & "About Us" section.
- [ ] **Assets:** Create company letterhead and slide deck master.
""")

    # 2. Update Changelog
    update_file('docs-site/support/changelog.md', r"""# 🚀 Changelog

### v1.9.1 (The Polish Update)
* **Fix:** **Wisdom Log Synchronization:** Resolved an issue where Workbook AI Compass insights were successfully generating but failing to render visually in the Insights Log.
* **Improvement:** **Action Plan Routing:** Adding a suggested task directly from a Workbook insight now correctly routes it to the AI Action Plan tab.
* **UI Polish:** **Journal Editor:** Optimized the template selector dropdown to ensure it scales cleanly on smaller mobile devices (like the Galaxy S21).
* **UI Polish:** **Header & Navigation:** Refined the header pulse animations to reduce visual distraction and improved the contrast of the main navigation logo.

### v1.9.0 (The Content Expansion Update)
* **New:** **Women for Recovery Workbook:** Added a completely new, 8-section specialty workbook focused on self-discovery, emotional awareness, boundaries, and overdose survival reframing.
* **Improvement:** **Specialty Themes:** Added a dedicated 'specialty' workbook category that triggers a unique purple (Heart) UI theme to distinguish it from traditional 12-Step or Dharma paths.

### v1.8.0 (The Medallion Update)
* **New:** **Monthly Milestones:** Added unique, high-fidelity circular recovery medallions for every month of the first year of sobriety.
* **Improvement:** **Reliable Sharing:** Implemented an image pre-loader in the Sobriety Hero to ensure medallions appear perfectly in social media exports.
* **Dev:** **Asset Pipeline:** Created Python-based automation for segmenting and processing transparent PWA assets.

Stay up to date with the latest features, fixes, and improvements to My Recovery Toolkit.

### v1.7.0 (The Virality Update)
* **New:** **Milestone Celebrations:** Hitting major clean-time milestones (30 days, 6 months, 1 year) now triggers a celebratory confetti burst on your dashboard and transforms your Sobriety Hero card into a highly shareable badge.
* **Improvement:** **AI Task Clarity:** Tasks generated by the AI Compass or Analysis Wizard now feature a clear "+7 Days" badge in your Action Plan to help you track when they were scheduled.
* **Improvement:** The image export tool now formats your milestones into a perfect square for seamless sharing on Instagram and Facebook.

### v1.6.0 (The Pre-Launch Polish Update)
* **New:** **Changelog Beacon:** You'll now receive a friendly toast notification on your dashboard when a new update is released.
* **New:** **Contextual Help:** Added a quick-access help icon to the main navigation header so you can easily access this User Guide from anywhere.
* **Improvement:** **AI Cost Shield:** Implemented clear rate-limiting for AI Analysis Wizard usage on the Free Tier, while maintaining unlimited access for Premium Supporters.

### v1.5.0 (The Supporter Update)
* **New:** **MRT Supporter Tier:** We have officially launched our Premium "Supporter" tier. By upgrading, you not only unlock unlimited AI Deep Dives, custom Journal Templates, and PDF Exports, but you also help keep the core crisis tools completely free for users who need them most.
* **New:** **Manage Subscription:** Seamless, secure integration with Stripe to manage your subscription directly from your Profile.

### v1.4.0 (The Momentum & Crisis Update)
* **New:** **Financial Freedom Tracker:** You can now enter your historical substance cost in your Profile. The dashboard will automatically calculate and display exactly how much money you've saved by staying clean.
* **New:** **The Urge Surfer:** Added a 5-minute interactive somatic grounding tool (accessible via the SOS menu and Tools tile). This feature uses the 5-4-3-2-1 method to help you ride out intense cravings, securely logging your victory to your journal when the wave passes.

### v1.3.1 (The Privacy & Marketing Update)
* **New:** **Right to be Forgotten:** You now have complete, automated control over your data. You can permanently delete your account directly from the Profile Data tab.
* **New:** **Native Link Tree:** Added a beautifully designed public `/links` page to easily share the app.

### v1.3.0 (The Wisdom & Intelligence Update)
* **New:** **Gemini 3.1 Pro Upgrade:** The "Analysis Wizard" and "Compass" now utilize Google's latest Gemini 3.1 Pro model.

### v1.0.0 (Initial Launch)
* **Feature:** Initial Public Release with Zero-Knowledge Client-Side Encryption (AES-GCM).
""")

    print("\n🎉 Post-Sprint Audit Complete. System state is synced.")

if __name__ == "__main__":
    main()