import os

# FENCE pattern to protect markdown backticks
FENCE = chr(96) * 3

# =============================================================================
# 1. docs/specs/05_TASKS.md
# =============================================================================
tasks_spec_content = r'''# 📐 Feature Spec: Tasks & Habits (The Ledger)

**Status:** Live (v2.1)
**Context:** High-density professional task management with AI action routing.

## 1. Overview
A streamlined interface for managing one-time tasks and recurring habits. Rebranded from "Quests" to "Tasks" to align with a professional recovery ledger aesthetic.

## 2. Smart Tabs (Routing Logic)
The system segregates tasks into four distinct lanes:
1. **This Week:** Active tasks where `dueDate` is less than 7 days from today AND `source` == 'manual'.
2. **Later:** Tasks where `dueDate` is exactly 7 days or more in the future AND `source` == 'manual'.
3. **Action Plan:** Tasks where `source` == 'ai'. This lane is reserved for growth items generated by the Compass (Workbooks) or Analysis Wizard (Journals).
4. **Log (History):** All tasks where `status` == 'completed' or where a recurring task was completed *today*. 
    * **Performance:** This view is virtualized using `react-virtuoso` and grouped hierarchically by Year -> Month to handle thousands of completed habits without UI lag.

## 3. Data Structure
**Collection:** `tasks`
| Field | Type | Description |
| :--- | :--- | :--- |
| `source` | string | 'manual' \| 'ai' (Determines tab routing) |
| `category` | string | 'Recovery', 'Health', 'Work', 'Life' |
| `priority` | string | 'High', 'Medium', 'Low' |
| `currentStreak`| number | Cumulative consecutive completions |
| `dueDate` | Timestamp | Next scheduled deadline |
| `recurrence` | Map | The full `RecurrenceConfig` object (type, interval, dayOfWeek, etc.) governing repetition. |

## 4. Technical Logic
* **Optimistic UI:** Toggle actions use React Query `onMutate` for zero-latency feedback.
* **Smart Reset:** Recurring tasks missed yesterday are automatically moved to "Today" with a streak penalty, preventing "schedule debt."
* **Future Task Safety:** If a user attempts to complete a task whose `dueDate` is strictly in the future, the optimistic UI update is intercepted by a Headless UI modal requiring explicit confirmation. This prevents accidental completion of future requirements.
'''

# =============================================================================
# 2. docs-site/guide/04-tasks-habits.md
# =============================================================================
tasks_guide_content = r'''# 📋 The Ledger (Tasks & Habits)

The Tasks module helps you build consistent routines and track actionable recovery steps.

## Smart Tabs
Your tasks are automatically routed into four distinct lanes to reduce overwhelm:
1. **This Week:** Tasks due today or within the next 6 days.
2. **Later:** Tasks scheduled exactly 7 days from now or further in the future.
3. **Action Plan:** Tasks generated automatically by the AI Compass (indicated by a purple Sparkles icon).
4. **Log:** Your history of completed tasks. 
   * *Note:* To keep the app running smoothly, your completed tasks are grouped by Year and Month. Tap a month to expand and view your historical wins!

## The "Smart Reset" System
We don't believe in "Schedule Debt" or guilt. 
* If you miss a daily recurring habit (like "Morning Meditation"), MRT doesn't leave it in the past. 
* It automatically drops your current streak to 0 (a gentle penalty) and **moves the due date to Today** so you can try again immediately.

## Creating a Task
Click the floating `+` button to add a task. You can set Priorities (High, Medium, Low) and advanced Recurring schedules (e.g., "The Last Friday of every month").

## Completing Future Tasks
If you attempt to check off a task that is scheduled for a future date (e.g., Tomorrow), the app will display a warning modal asking you to confirm. This prevents you from accidentally clearing out tasks you actually need to do later in the week.
'''

# =============================================================================
# 3. docs/SCHEMA_ARCHITECTURE.md
# =============================================================================
schema_content = r'''# 🗄️ Schema Architecture & Data Graph

**Storage Engine:** Cloud Firestore (NoSQL)
**Encryption Strategy:** Client-Side AES-GCM (Content fields only)

## 1. High-Level Topology

__FENCE__mermaid
graph TD
    root[🔥 Firestore Root]
    
    root --> users[📂 users]
    users --> userDoc[📄 User Profile]
    userDoc --> workbook_progress[📂 workbook_progress]
    userDoc --> templates[📂 templates]
    
    root --> journals[📂 journals]
    root --> tasks[📂 tasks]
    root --> insights[📂 insights]
    root --> ai_logs[📂 ai_logs]
    root --> feedback[📂 feedback]
    root --> service[📂 service (Planned)]
__FENCE__

## 2. Collection Definitions

### `users/{uid}`
* **Purpose:** Profile, Auth, Billing, & Settings.
* **Fields:**
    * `encryptionSalt` (String): Public salt needed to derive key.
    * `pinVerifier` (String): Hash(PIN + Salt) to verify PIN correctness without storing it.
    * `sobrietyDate` (Timestamp): Metrics base.
    * `role` (String): 'user' | 'admin'. Controls UI access.
    * `tier` (String): 'free' | 'premium'. Controls feature access.
    * `stripeCustomerId` (String): Reference for subscription management (Optional).
    * `sponsorName` & `sponsorPhone` (String): Unencrypted. Used for SOS dialer.
    * `hasCompletedOnboarding` (Boolean): Determines if user needs forced routing to Profile setup.
    * `lastExportAt` (Timestamp): Used for the 7-day Backup Reminder.
    * `usage_limits` (Map): Timestamps (`lastWeeklyInsight`, `lastDeepDive`) to throttle AI costs.

### `journals/{entryId}`
* **Purpose:** Daily logs, Vitality logs, and reflections.
* **Fields:**
    * `uid` (String): Owner ID.
    * `content` (String): **ENCRYPTED BLOB** (format: `iv:ciphertext`).
    * `isEncrypted` (Boolean): Flag for legacy plain text data handling.
    * `moodScore` (Int): **UNENCRYPTED** (Allows fast dashboard stats).
    * `sentiment` (String): AI-derived sentiment (e.g. 'Positive', 'Negative').
    * `tags` (Array): **UNENCRYPTED** (e.g., `["Vitality", "Movement"]`).
    * `weather` (Map): Snapshot of environment `{ temp, condition }`.

### `tasks/{taskId}`
* **Purpose:** Gamification, Habits, and AI Action Plans.
* **Encryption:** Unencrypted to allow background stats and streak evaluations.
* **Fields:**
    * `title` (String): Task name.
    * `category` (String): 'Recovery' | 'Health' | 'Life' | 'Work'.
    * `source` (String): 'manual' | 'ai'. (AI tasks map to the Action Plan tab).
    * `priority` (String): 'High' | 'Medium' | 'Low'.
    * `status` (String): 'pending' | 'completed'.
    * `currentStreak` (Int): Consecutive completions.
    * `recurrence` (Map): The full `RecurrenceConfig` logic object (e.g., `{ type: 'monthly-relative', weekOfMonth: 1, dayOfWeek: 1 }`).
    * `dueDate` & `lastCompletedAt` (Timestamp).

### `insights/{insightId}`
* **Purpose:** AI-generated analysis of journals/workbooks.
* **Fields:**
    * `type` (String): 'journal' | 'workbook'.
    * `summary` (String): The AI's output.
    * `pillars` (Map): Structured breakdown (understanding, growth, blind_spots).
    * `strengths` & `risks` (Array): Listed points for UI rendering.
    * `suggested_actions` (Array): 3 specific strings to be converted into Tasks.

### `feedback/{reportId}`
* **Purpose:** User bug reports and suggestions.
* **Encryption:** **NONE** (To allow debugging without user PIN).
* **Fields:**
    * `category`: 'bug' | 'suggestion' | 'content'.
    * `buildHash`: Commit hash for version tracing.
    * `environment`: 'DEV' | 'UAT' | 'PRODUCTION'.
    * `vaultUnlocked`: Boolean.
    * `route` & `userAgent`: Strings.

### `service/{serviceId}` (Planned - Project 05)
* **Purpose:** "Digital Rolodex" for sponsors to manage sponsees/commitments.
* **Fields:**
    * `type` (String): 'sponsee' | 'commitment'.
    * `name`, `contactInfo`, `notes` (Strings): **ENCRYPTED**.
    * `status` (String): 'Active' | 'Alumni' (Unencrypted for filtering).
    * `nextMeeting` (Timestamp): **UNENCRYPTED** (Allows push notifications).

## 3. Query Strategy
* **Journal History:** Query by `uid`, order by `createdAt`. Requires client-side decryption loop.
* **Stats:** Query `moodScore` (Journal) or `completed` (Tasks) directly for dashboards (fast, no decrypt needed).
'''

# =============================================================================
# 4. docs/SPRINT_BOARD.md
# =============================================================================
sprint_board_content = r'''# 🏃 Active Sprint Board
**Sprint:** 4.8 "The Crucible: Dogfooding & Polish"
**Start Date:** 2026-03-04
**Goal:** Perform rigorous manual QA ("Dogfooding") to identify and eradicate UX friction in Tasks, Vitality, Wisdom, and Insights before beginning the Service Module.

## ✅ Sprints 1-3: Foundation & Core Polish (Completed)
- [x] Auth UI, Onboarding Redirect, Dashboard Identity, Journal Cache, and basic UI density.

## ✅ Sprint 4.0 - 4.7: Hardening & Visuals (Completed)
- [x] Unit Tests (`useJournalOperations`, `useTaskOperations`).
- [x] Wake Lock API for Breathwork.
- [x] Gradient Charts & Word Cloud Filters.
- [x] Triage Inbox Rework (Accordion Grouping).

## 🟡 Sprint 4.8: The Dogfooding Phase (Active)
- [x] **Sector 4: The Ledger (Tasks):**
  - [x] The Timezone Test: Due dates now anchor to local Noon to prevent UTC midnight shifts.
  - [x] The "Debt" Test: Smart Resets decouple visual completion from background lifecycle status.
  - [x] The Overflow Test: Task titles wrap elegantly; mobile layout is stable.
  - [x] The "Future Task" Test: Injected Headless UI safety intercept modal for premature completions.
  - [x] The "Log Scalability" Test: Migrated History tab to `react-virtuoso` with Year/Month hierarchical grouping.
- [ ] **Sector 5: The Pulse (Vitality):** Test real-world feel of the breathwork pacer, mobile rendering, and bio-rhythm edge cases.
- [ ] **Sector 6: The Compass (Wisdom):** Test auto-save latency, mobile keyboard UX, and AI coaching prompt quality.
- [ ] **Sector 7: Insights Log:** Test rendering of long AI responses, markdown parsing, and filter interactions.

## 🧊 Backlog (Sprint 5+)
- [ ] **PROJ-05:** The "Lisa" Service Module (Encrypted Rolodex).
- [ ] **PROJ-06:** Rich Media & Memory (Photo Attachments).
- [ ] **PROJ-07:** The Launch Engine (Stripe, Demo Mode).
- [ ] **PROJ-08:** Recovery Tools (CBT & Mindfulness aids).
'''


def write_file(path, content):
    dirname = os.path.dirname(path)
    if dirname: 
        os.makedirs(dirname, exist_ok=True)
    # Apply FENCE replacement safely
    final_content = content.replace("__FENCE__", FENCE).strip() + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(final_content)
    print(f"✅ Synced: {path}")

if __name__ == "__main__":
    write_file("docs/specs/05_TASKS.md", tasks_spec_content)
    write_file("docs-site/guide/04-tasks-habits.md", tasks_guide_content)
    write_file("docs/SCHEMA_ARCHITECTURE.md", schema_content)
    write_file("docs/SPRINT_BOARD.md", sprint_board_content)
    print("✨ Documentation Audit Complete. All files synchronized with codebase reality.")