import os
import json
import re

FENCE = chr(96) * 3

def sanitize_key(name):
    """Converts a file or folder name into a valid JavaScript property key."""
    # Remove file extension if present
    if '.' in name:
        name = name.rsplit('.', 1)[0]
    # Replace non-alphanumeric characters with underscores
    clean_name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Ensure it doesn't start with a number
    if clean_name and clean_name[0].isdigit():
        clean_name = '_' + clean_name
    # Make it camelCase-friendly (lowercase the first letter if it's caps)
    if clean_name:
        clean_name = clean_name[0].lower() + clean_name[1:]
    return clean_name

def build_asset_tree():
    print(f"[{FENCE}] Initiating PROJ-24: Asset Index Generator [{FENCE}]")
    
    public_dir = "public"
    if not os.path.exists(public_dir):
        print(f"⚠️ Error: Could not find '{public_dir}' directory.")
        return

    asset_tree = {}

    for root, dirs, files in os.walk(public_dir):
        # Ignore hidden directories like .DS_Store
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        
        for file in files:
            if file.startswith('.'):
                continue
                
            # Get the relative path from the public directory
            # e.g., "Marketing/Screenshots/scn_dashboard.webp"
            rel_path = os.path.relpath(os.path.join(root, file), public_dir)
            
            # Split into parts
            parts = rel_path.split(os.sep)
            
            # Navigate/build the nested dictionary
            current_level = asset_tree
            for folder in parts[:-1]:
                folder_key = sanitize_key(folder)
                if folder_key not in current_level:
                    current_level[folder_key] = {}
                current_level = current_level[folder_key]
                
            # Add the file to the current level
            file_key = sanitize_key(parts[-1])
            # Ensure web-safe forward slashes
            web_path = "/" + rel_path.replace("\\", "/")
            current_level[file_key] = web_path

    # Convert the dictionary to formatted JSON, then wrap it in TypeScript
    ts_object = json.dumps(asset_tree, indent=2)
    
    ts_content = f"""/**
 * AUTO-GENERATED ASSET INDEX (PROJ-24)
 * Do not edit this file manually.
 * Run `python3 scripts/generate_asset_index.py` to regenerate.
 */

export const ASSETS = {ts_object} as const;

export type AssetPath = typeof ASSETS;
"""

    # Ensure the target directory exists
    os.makedirs("src/data", exist_ok=True)
    
    target_file = "src/data/assets.ts"
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(ts_content)
        
    print(f"✅ Successfully crawled '{public_dir}' and generated {target_file}")

if __name__ == "__main__":
    build_asset_tree()