import os

def update_file(filepath, updates):
    if not os.path.exists(filepath):
        print(f"⚠️ File not found: {filepath}")
        return

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    for old_text, new_text in updates:
        if old_text in content:
            content = content.replace(old_text, new_text)
        else:
            print(f"⚠️ Could not find target text in {filepath}:\n'{old_text[:50]}...'")

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"✅ Updated: {filepath}")

# ---------------------------------------------------------
# 1. Update 04_WORKBOOKS.md
# ---------------------------------------------------------
wb_updates = [
    (
        "## 2. AI Integration\n* **Coach:** Individual feedback via `getGeminiCoaching`.\n* **Compass:** Aggregate section analysis via `analyzeFullWorkbook`.",
        "## 2. Reading Experience (Zen Mode)\n* **Focus:** `WorkbookSession.tsx` implements a full-screen, distraction-free reading layer using `@tailwindcss/typography`.\n* **Data Safety:** Answers are auto-saved to Firestore via `useAutoSave` every 2 seconds. Data is encrypted client-side *before* transmission.\n\n## 3. AI Integration\n* **Coach:** On-demand, individual question feedback via `getGeminiCoaching`.\n* **Compass:** Aggregate section analysis via `analyzeFullWorkbook`. Suggested actions added to Habits are tagged with `source: 'ai'` to route them to the Action Plan tab.\n\n## 4. Gamification\n* **Chapters Mastered:** Calculated locally in `Workbooks.tsx` by cross-referencing completed answers against the required questions in the static `WORKBOOKS` schema."
    )
]

# ---------------------------------------------------------
# 2. Update 07_GAMIFICATION.md
# ---------------------------------------------------------
game_updates = [
    (
        "| Workbook Answer | 15 XP |",
        "| Workbook Answer | 15 XP |\n| Chapter Mastered | Status Milestone (Calculated locally) |"
    )
]

# ---------------------------------------------------------
# 3. Update 05_TASKS.md
# ---------------------------------------------------------
task_updates = [
    (
        "3. **Action Plan:** Tasks where `source` == 'ai'. This lane is reserved for growth items generated by the Compass or Analysis Wizard.",
        "3. **Action Plan:** Tasks where `source` == 'ai'. This lane is reserved for growth items generated by the Compass (Workbooks) or Analysis Wizard (Journals)."
    )
]

# ---------------------------------------------------------
# 4. Update SPRINT_BOARD.md
# ---------------------------------------------------------
sprint_updates = [
    (
        "## 📌 To Do (Project 03)\n- [ ] **Typography:** Implement @tailwindcss/typography for workbook prose.\n- [ ] **Focus Mode:** Design \"Reading Mode\" to hide UI distractions.\n- [ ] **Auto-save:** Implement debounced listeners for workbook answers.",
        "## 📌 To Do\n- [ ] Documentation and final UAT for Project 03.\n\n## ✅ Done (This Sprint)\n- [x] **Project 03:** Implemented `@tailwindcss/typography` for workbook prose.\n- [x] **Project 03:** Built \"Zen Mode\" reading interface.\n- [x] **Project 03:** Deployed encrypted auto-save engine.\n- [x] **Project 03:** Integrated Gamification (Chapters Mastered)."
    )
]

if __name__ == "__main__":
    print("🔄 Synchronizing Documentation...")
    update_file("docs/specs/04_WORKBOOKS.md", wb_updates)
    update_file("docs/specs/07_GAMIFICATION.md", game_updates)
    update_file("docs/specs/05_TASKS.md", task_updates)
    update_file("docs/SPRINT_BOARD.md", sprint_updates)
    print("✨ Documentation Drift Resolved.")