#!/usr/bin/env python3
from __future__ import annotations
"""
Generic replacement for the old one-off `close_ticket.py` pattern.

The `ticket-close` skill used to hand-generate a throwaway, hardcoded Python
script per ticket (one `safe_replace` call per file, per PROJ-ID, discarded
after use). This script does the same mechanical edits, parameterized by
PROJ-ID, so the pattern is written once and diffable like any other code
change instead of regenerated by an LLM every ticket close.

What it automates (the parts that are pure text templating):
  - docs/projects/<ID>_*.md          -> flip Status field to "Shipped"
  - docs/ACTIVE_CYCLE.md             -> add a line under "Resolved This Cycle"
  - docs/ROADMAP.md                  -> add a line under "RECENTLY SHIPPED"
  - docs-site/support/changelog.md   -> add a version entry, but ONLY when
                                         --public-note is explicitly passed
                                         (see PROJ-69). --summary never
                                         reaches this file — it's internal.

What it deliberately does NOT automate (these need judgment, not templating):
  - Whether a ticket is user-visible at all (ticket-close skill Check 0)
  - Wording of --public-note itself, and the version number to bump to
  - docs-site/guide/ user-guide drift (ticket-close skill Check 3, blocking)
  - tech-debt scan / ZK check (ticket-close skill Checks 5 and 6)
Run the `ticket-close` skill for those.

Usage:
  python scripts/sync_ticket_docs.py --proj PROJ-59 --summary "One-line description of what shipped."
  python scripts/sync_ticket_docs.py --proj PROJ-59 --summary "..." --apply

  # User-visible ticket: also prepend a public changelog entry.
  python scripts/sync_ticket_docs.py --proj PROJ-59 --summary "..." \\
      --public-note "Plain-language description for end users." --version 1.9.0 --apply

Defaults to a dry run (prints intended changes, writes nothing) unless --apply is passed.

--public-note must never contain a PROJ-ID, a file/component name, or other
internal detail (PROJ-69) — the script refuses to run if it looks like it does.
"""
import argparse
import glob
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ACTIVE_CYCLE = REPO_ROOT / "docs" / "ACTIVE_CYCLE.md"
ROADMAP = REPO_ROOT / "docs" / "ROADMAP.md"
CHANGELOG = REPO_ROOT / "docs-site" / "support" / "changelog.md"

STATUS_LINE_RE = re.compile(r"^(\*{0,2}Status\*{0,2}:\*{0,2}\s*).*$", re.MULTILINE)
# Spec titles are inconsistent about a leading "#" — some files (e.g. 26, 38, 41)
# omit the markdown heading marker entirely — so it's optional here.
TITLE_RE = re.compile(r"^#?\s*[^\w]*\s*(?:Project\s+(?:PROJ-)?\d+:\s*)?(.+?)\s*$")

# Patterns that mean --public-note is leaking internal detail into the public
# changelog — the exact mistake PROJ-69 exists to stop. Kept deliberately
# broad/simple (false positives just mean re-wording the note, which is cheap;
# a missed leak is not).
LEAK_PATTERNS = [
    re.compile(r"PROJ-\d+", re.IGNORECASE),
    re.compile(r"\bsrc/"),
    re.compile(r"\.tsx?\b"),
    re.compile(r"\.py\b"),
]


def find_leak(note: str) -> str | None:
    for pattern in LEAK_PATTERNS:
        if pattern.search(note):
            return pattern.pattern
    return None


def find_spec_file(proj_num: str) -> Path:
    matches = [
        Path(p)
        for p in glob.glob(str(REPO_ROOT / "docs" / "projects" / f"{proj_num}_*.md"))
    ]
    if not matches:
        sys.exit(f"No spec file found matching docs/projects/{proj_num}_*.md")
    if len(matches) > 1:
        sys.exit(f"Multiple spec files matched docs/projects/{proj_num}_*.md: {matches}")
    return matches[0]


def extract_name(spec_content: str) -> str:
    first_line = spec_content.splitlines()[0]
    m = TITLE_RE.match(first_line)
    return m.group(1) if m else first_line.lstrip("# ").strip()


def apply_status_shipped(content: str) -> tuple[str, bool]:
    if not STATUS_LINE_RE.search(content):
        return content, False
    new_content, count = STATUS_LINE_RE.subn(r"\1✅ Shipped", content, count=1)
    return new_content, count > 0


def insert_after_heading(content: str, heading_pattern: str, new_line: str) -> tuple[str, bool]:
    match = re.search(rf"^({heading_pattern}.*)$", content, re.MULTILINE)
    if not match:
        return content, False
    insert_at = match.end()
    return content[:insert_at] + "\n" + new_line + content[insert_at:], True


def insert_changelog_entry(content: str, version: str, note: str, category: str) -> tuple[str, bool]:
    # Changelog entries are blank-line-separated blocks (## header, ### category,
    # bullets), unlike the single-bullet-under-heading shape the other two files
    # use, so this gets its own insertion logic rather than reusing
    # insert_after_heading.
    match = re.search(r"^(#\s+.*Changelog.*)$", content, re.MULTILINE)
    if not match:
        return content, False
    insert_at = match.end()
    block = f"## [v{version}] - {date.today().isoformat()}\n### {category}\n- {note}\n"
    rest = content[insert_at:].lstrip("\n")
    return content[:insert_at] + "\n\n" + block + "\n" + rest, True


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--proj", required=True, help="PROJ-ID, e.g. PROJ-59")
    parser.add_argument("--summary", required=True, help="One-line internal shipped summary (spec/ACTIVE_CYCLE/ROADMAP only — never reaches the public changelog)")
    parser.add_argument("--public-note", help="Plain-language, end-user-facing changelog note. Omit entirely for internal-only tickets — see ticket-close skill Check 0.")
    parser.add_argument("--version", help="Public version number for --public-note, e.g. 1.9.0. Required together with --public-note.")
    parser.add_argument("--category", default="🛠️ Update", help="Changelog section heading for --public-note's entry, e.g. '✨ New Feature' or '🐛 Bug Fixes'. Default: '🛠️ Update'.")
    parser.add_argument("--apply", action="store_true", help="Write changes (default is dry run)")
    args = parser.parse_args()

    if bool(args.public_note) != bool(args.version):
        sys.exit("--public-note and --version must be passed together.")

    if args.public_note:
        leak = find_leak(args.public_note)
        if leak:
            sys.exit(
                f"--public-note appears to contain internal detail (matched {leak!r}). "
                "The public changelog must not reference ticket IDs, file paths, or "
                "internal component names — reword in plain, user-facing language."
            )

    proj_id = args.proj.upper()
    m = re.match(r"PROJ-(\d+)", proj_id)
    if not m:
        sys.exit(f"--proj must look like PROJ-59, got {args.proj!r}")
    proj_num = m.group(1)

    spec_path = find_spec_file(proj_num)
    spec_content = spec_path.read_text(encoding="utf-8")
    name = extract_name(spec_content)

    print(f"Resolved {proj_id} -> {spec_path.relative_to(REPO_ROOT)} ({name!r})\n")

    # Each entry: (path, new_content, [display lines describing the change])
    changes = []

    old_status_line = next((l for l in spec_content.splitlines() if STATUS_LINE_RE.match(l)), None)
    new_spec_content, changed = apply_status_shipped(spec_content)
    if not changed:
        print(f"WARNING: no Status field found in {spec_path.name} — skipping status update.")
    else:
        new_status_line = next(l for l in new_spec_content.splitlines() if STATUS_LINE_RE.match(l))
        changes.append((spec_path, new_spec_content, [f"  - {old_status_line}", f"  + {new_status_line}"]))

    active_cycle_content = ACTIVE_CYCLE.read_text(encoding="utf-8")
    if proj_id in active_cycle_content:
        print(f"WARNING: {proj_id} already referenced in {ACTIVE_CYCLE.name} — skipping (idempotency guard).")
    else:
        new_line = f"- [x] **{proj_id}:** {name} — {args.summary}"
        new_active_cycle, changed = insert_after_heading(
            active_cycle_content, r"## ✅ Resolved This Cycle", new_line
        )
        if not changed:
            print(f"WARNING: '## ✅ Resolved This Cycle' heading not found in {ACTIVE_CYCLE.name}.")
        else:
            changes.append((ACTIVE_CYCLE, new_active_cycle, [f"  + {new_line}"]))

    roadmap_content = ROADMAP.read_text(encoding="utf-8")
    if proj_id in roadmap_content:
        print(f"WARNING: {proj_id} already referenced in {ROADMAP.name} — skipping (idempotency guard).")
    else:
        new_line = f"* `{proj_id}` {name} ({args.summary})"
        new_roadmap, changed = insert_after_heading(roadmap_content, r"## ✅ RECENTLY SHIPPED", new_line)
        if not changed:
            print(f"WARNING: '## ✅ RECENTLY SHIPPED' heading not found in {ROADMAP.name}.")
        else:
            changes.append((ROADMAP, new_roadmap, [f"  + {new_line}"]))

    if not args.public_note:
        print("No public changelog entry (internal-only change).")
    else:
        changelog_content = CHANGELOG.read_text(encoding="utf-8")
        if f"[v{args.version}]" in changelog_content:
            print(f"WARNING: v{args.version} already referenced in {CHANGELOG.name} — skipping (idempotency guard).")
        else:
            new_changelog, changed = insert_changelog_entry(
                changelog_content, args.version, args.public_note, args.category
            )
            if not changed:
                print(f"WARNING: Changelog H1 heading not found in {CHANGELOG.name}.")
            else:
                changes.append((
                    CHANGELOG,
                    new_changelog,
                    [f"  + ## [v{args.version}] - {date.today().isoformat()}",
                     f"  + ### {args.category}",
                     f"  + - {args.public_note}"],
                ))

    print(f"\n{'APPLYING' if args.apply else 'DRY RUN — would apply'} {len(changes)} file change(s):\n")
    for path, _new, display_lines in changes:
        print(f"--- {path.relative_to(REPO_ROOT)} ---")
        for line in display_lines:
            print(line)
        print()

    if args.apply:
        for path, new, _display_lines in changes:
            path.write_text(new, encoding="utf-8")
        print("Applied. Remaining manual steps (not automated — need judgment):")
    else:
        print("Dry run only — nothing written. Re-run with --apply to write these changes.")
        print("\nRemaining manual steps regardless (not automated — need judgment):")

    print("  - Run the `ticket-close` skill for user-guide drift, tech-debt scan, and ZK check.")


if __name__ == "__main__":
    main()
