#!/usr/bin/env python3
"""
Generic replacement for the old one-off `close_ticket.py` pattern.

The `ticket-close` skill used to hand-generate a throwaway, hardcoded Python
script per ticket (one `safe_replace` call per file, per PROJ-ID, discarded
after use). This script does the same mechanical edits, parameterized by
PROJ-ID, so the pattern is written once and diffable like any other code
change instead of regenerated by an LLM every ticket close.

What it automates (the parts that are pure text templating):
  - docs/projects/<ID>_*.md   -> flip Status field to "Shipped"
  - docs/ACTIVE_CYCLE.md      -> add a line under "Resolved This Cycle"
  - docs/ROADMAP.md           -> add a line under "RECENTLY SHIPPED"

What it deliberately does NOT automate (these need judgment, not templating):
  - docs-site/support/changelog.md (version-bump semantics)
  - docs-site/guide/ user-guide drift (ticket-close skill Check 3, blocking)
  - tech-debt scan / ZK check (ticket-close skill Checks 5 and 6)
Run the `ticket-close` skill for those.

Usage:
  python scripts/sync_ticket_docs.py --proj PROJ-59 --summary "One-line description of what shipped."
  python scripts/sync_ticket_docs.py --proj PROJ-59 --summary "..." --apply

Defaults to a dry run (prints intended changes, writes nothing) unless --apply is passed.
"""
import argparse
import glob
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ACTIVE_CYCLE = REPO_ROOT / "docs" / "ACTIVE_CYCLE.md"
ROADMAP = REPO_ROOT / "docs" / "ROADMAP.md"

STATUS_LINE_RE = re.compile(r"^(\*{0,2}Status\*{0,2}:\*{0,2}\s*).*$", re.MULTILINE)
# Spec titles are inconsistent about a leading "#" — some files (e.g. 26, 38, 41)
# omit the markdown heading marker entirely — so it's optional here.
TITLE_RE = re.compile(r"^#?\s*[^\w]*\s*(?:Project\s+(?:PROJ-)?\d+:\s*)?(.+?)\s*$")


def find_spec_file(proj_num: str) -> Path:
    matches = [
        Path(p)
        for p in glob.glob(str(REPO_ROOT / "docs" / "projects" / f"{proj_num}_*.md"))
    ]
    if not matches:
        sys.exit(f"No spec file found matching docs/projects/{proj_num}_*.md")
    if len(matches) > 1:
        sys.exit(f"Multiple spec files matched docs/projects/{proj_num}_*.md: {matches}")
    return matches[0]


def extract_name(spec_content: str) -> str:
    first_line = spec_content.splitlines()[0]
    m = TITLE_RE.match(first_line)
    return m.group(1) if m else first_line.lstrip("# ").strip()


def apply_status_shipped(content: str) -> tuple[str, bool]:
    if not STATUS_LINE_RE.search(content):
        return content, False
    new_content, count = STATUS_LINE_RE.subn(r"\1✅ Shipped", content, count=1)
    return new_content, count > 0


def insert_after_heading(content: str, heading_pattern: str, new_line: str) -> tuple[str, bool]:
    match = re.search(rf"^({heading_pattern}.*)$", content, re.MULTILINE)
    if not match:
        return content, False
    insert_at = match.end()
    return content[:insert_at] + "\n" + new_line + content[insert_at:], True


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--proj", required=True, help="PROJ-ID, e.g. PROJ-59")
    parser.add_argument("--summary", required=True, help="One-line shipped summary")
    parser.add_argument("--apply", action="store_true", help="Write changes (default is dry run)")
    args = parser.parse_args()

    proj_id = args.proj.upper()
    m = re.match(r"PROJ-(\d+)", proj_id)
    if not m:
        sys.exit(f"--proj must look like PROJ-59, got {args.proj!r}")
    proj_num = m.group(1)

    spec_path = find_spec_file(proj_num)
    spec_content = spec_path.read_text(encoding="utf-8")
    name = extract_name(spec_content)

    print(f"Resolved {proj_id} -> {spec_path.relative_to(REPO_ROOT)} ({name!r})\n")

    # Each entry: (path, new_content, [display lines describing the change])
    changes = []

    old_status_line = next((l for l in spec_content.splitlines() if STATUS_LINE_RE.match(l)), None)
    new_spec_content, changed = apply_status_shipped(spec_content)
    if not changed:
        print(f"WARNING: no Status field found in {spec_path.name} — skipping status update.")
    else:
        new_status_line = next(l for l in new_spec_content.splitlines() if STATUS_LINE_RE.match(l))
        changes.append((spec_path, new_spec_content, [f"  - {old_status_line}", f"  + {new_status_line}"]))

    active_cycle_content = ACTIVE_CYCLE.read_text(encoding="utf-8")
    if proj_id in active_cycle_content:
        print(f"WARNING: {proj_id} already referenced in {ACTIVE_CYCLE.name} — skipping (idempotency guard).")
    else:
        new_line = f"- [x] **{proj_id}:** {name} — {args.summary}"
        new_active_cycle, changed = insert_after_heading(
            active_cycle_content, r"## ✅ Resolved This Cycle", new_line
        )
        if not changed:
            print(f"WARNING: '## ✅ Resolved This Cycle' heading not found in {ACTIVE_CYCLE.name}.")
        else:
            changes.append((ACTIVE_CYCLE, new_active_cycle, [f"  + {new_line}"]))

    roadmap_content = ROADMAP.read_text(encoding="utf-8")
    if proj_id in roadmap_content:
        print(f"WARNING: {proj_id} already referenced in {ROADMAP.name} — skipping (idempotency guard).")
    else:
        new_line = f"* `{proj_id}` {name} ({args.summary})"
        new_roadmap, changed = insert_after_heading(roadmap_content, r"## ✅ RECENTLY SHIPPED", new_line)
        if not changed:
            print(f"WARNING: '## ✅ RECENTLY SHIPPED' heading not found in {ROADMAP.name}.")
        else:
            changes.append((ROADMAP, new_roadmap, [f"  + {new_line}"]))

    print(f"\n{'APPLYING' if args.apply else 'DRY RUN — would apply'} {len(changes)} file change(s):\n")
    for path, _new, display_lines in changes:
        print(f"--- {path.relative_to(REPO_ROOT)} ---")
        for line in display_lines:
            print(line)
        print()

    if args.apply:
        for path, new, _display_lines in changes:
            path.write_text(new, encoding="utf-8")
        print("Applied. Remaining manual steps (not automated — need judgment):")
    else:
        print("Dry run only — nothing written. Re-run with --apply to write these changes.")
        print("\nRemaining manual steps regardless (not automated — need judgment):")

    print("  - docs-site/support/changelog.md: prepend a version entry.")
    print("  - Run the `ticket-close` skill for user-guide drift, tech-debt scan, and ZK check.")


if __name__ == "__main__":
    main()
