/**
 * AUTO-GENERATED ASSET INDEX (PROJ-24)
 * Do not edit this file manually.
 * Run `python3 scripts/generate_asset_index.py` to regenerate.
 */

export const ASSETS = {
  "firebase_messaging_sw": "/firebase-messaging-sw.js",
  "pwa_512x512": "/pwa-512x512.png",
  "apple_touch_icon_180x180": "/apple-touch-icon-180x180.png",
  "favicon": "/favicon.ico",
  "favicon_16x16": "/favicon-16x16.png",
  "favicon_32x32": "/favicon-32x32.png",
  "pwa_192x192": "/pwa-192x192.png",
  "apple_touch_icon": "/apple-touch-icon.png",
  "maskable_icon_512x512": "/maskable-icon-512x512.png",
  "personas": {
    "jordan": {
      "headshot": "/personas/jordan/headshot.webp",
      "full_body": "/personas/jordan/full_body.webp",
      "looking_left": "/personas/jordan/looking_left.webp"
    },
    "walt": {
      "headshot": "/personas/walt/headshot.webp",
      "full_body": "/personas/walt/full_body.webp",
      "looking_left": "/personas/walt/looking_left.webp"
    },
    "ned": {
      "headshot": "/personas/ned/headshot.webp",
      "full_body": "/personas/ned/full_body.webp",
      "looking_left": "/personas/ned/looking_left.webp"
    },
    "lisa": {
      "headshot": "/personas/lisa/headshot.webp",
      "full_body": "/personas/lisa/full_body.webp",
      "looking_left": "/personas/lisa/looking_left.webp"
    },
    "maya": {
      "headshot": "/personas/maya/headshot.webp",
      "full_body": "/personas/maya/full_body.webp",
      "looking_left": "/personas/maya/looking_left.webp"
    },
    "david": {
      "headshot": "/personas/david/headshot.webp",
      "full_body": "/personas/david/full_body.webp",
      "looking_left": "/personas/david/looking_left.webp"
    }
  },
  "chips": {
    "medallion_07": "/Chips/medallion_07.webp",
    "medallion_06": "/Chips/medallion_06.webp",
    "medallion_10": "/Chips/medallion_10.webp",
    "medallion_02": "/Chips/medallion_02.webp",
    "medallion_04": "/Chips/medallion_04.webp",
    "medallion_05": "/Chips/medallion_05.webp",
    "medallion_03": "/Chips/medallion_03.webp",
    "medallion_12": "/Chips/medallion_12.webp",
    "medallion_01": "/Chips/medallion_01.webp",
    "medallion_11": "/Chips/medallion_11.webp",
    "medallion_08": "/Chips/medallion_08.webp",
    "medallion_09": "/Chips/medallion_09.webp"
  },
  "raw_assets": {
    "ned_The_Pink_Cloud": "/raw_assets/Ned_The_Pink_Cloud.jpg",
    "mRT_Logo_Transparent": "/raw_assets/MRT_Logo_Transparent.png",
    "ned_headshot": "/raw_assets/ned_headshot.png",
    "ned_bio": "/raw_assets/ned_bio.jpg"
  },
  "marketing": {
    "feature_graphic": "/Marketing/feature_graphic.png",
    "ned_The_Pink_Cloud": "/Marketing/Ned_The_Pink_Cloud.webp",
    "lisa_The_Service_Pro": "/Marketing/Lisa_The_Service_Pro.webp",
    "snc_tools_personalities": "/Marketing/snc_tools_personalities.webp",
    "walt_The_Zen_Master": "/Marketing/Walt_The_Zen_Master.webp",
    "mRT_Logo_Transparent": "/Marketing/MRT_Logo_Transparent.webp",
    "scns_tools_dents": "/Marketing/scns_tools_dents.webp",
    "social_media_images": {
      "adv_progress_not_perfection": "/Marketing/social_media_images/adv_progress_not_perfection.png",
      "adv_one_day_at_a_time": "/Marketing/social_media_images/adv_one_day_at_a_time.png",
      "adv_halt": "/Marketing/social_media_images/adv_halt.png",
      "adv_easy_does_it": "/Marketing/social_media_images/adv_easy_does_it.png",
      "adv_one_day_at_a_time_2": "/Marketing/social_media_images/adv_one_day_at_a_time_2.png",
      "adv_feelings": "/Marketing/social_media_images/adv_feelings.png",
      "adv_sick_as_secrets": "/Marketing/social_media_images/adv_sick_as_secrets.png",
      "adv_keep_it_simple": "/Marketing/social_media_images/adv_keep_it_simple.png",
      "adv_one_breath": "/Marketing/social_media_images/adv_one_breath.png",
      "adv_miracle_happens": "/Marketing/social_media_images/adv_miracle_happens.png"
    },
    "screenshots": {
      "scn_profile_05_data": "/Marketing/Screenshots/scn_profile_05_data.webp",
      "scn_dashboard_04_nav": "/Marketing/Screenshots/scn_dashboard_04_nav.webp",
      "scn_profile_security": "/Marketing/Screenshots/scn_profile_security.webp",
      "scn_journal_voice_record_03": "/Marketing/Screenshots/scn_journal_voice_record_03.webp",
      "scn_tools_urge_surfer": "/Marketing/Screenshots/scn_tools_urge_surfer.webp",
      "scn_sos_crisis_support": "/Marketing/Screenshots/scn_sos_crisis_support.webp",
      "scn_vitality_movement": "/Marketing/Screenshots/scn_vitality_movement.webp",
      "scn_daily_crossword": "/Marketing/Screenshots/scn_daily_crossword.webp",
      "scn_journal_templates": "/Marketing/Screenshots/scn_journal_templates.webp",
      "scn_workbook_question": "/Marketing/Screenshots/scn_workbook_question.webp",
      "scn_profile_general": "/Marketing/Screenshots/scn_profile_general.webp",
      "scn_wison_rd": "/Marketing/Screenshots/scn_wison_rd.webp",
      "scn_journal_history": "/Marketing/Screenshots/scn_journal_history.webp",
      "scn_wisdom_main": "/Marketing/Screenshots/scn_wisdom_main.webp",
      "scn_games_hub": "/Marketing/Screenshots/scn_games_hub.webp",
      "scn_profile_04_data": "/Marketing/Screenshots/scn_profile_04_data.webp",
      "scn_dashboard_02_clean_time": "/Marketing/Screenshots/scn_dashboard_02_clean_time.webp",
      "scn_goal_ladder": "/Marketing/Screenshots/scn_goal_ladder.webp",
      "scn_navbar": "/Marketing/Screenshots/scn_navbar.webp",
      "scn_dashboard": "/Marketing/Screenshots/scn_dashboard.webp",
      "scn_journal_insights": "/Marketing/Screenshots/scn_journal_insights.webp",
      "scn_profile_01_main": "/Marketing/Screenshots/scn_profile_01_main.webp",
      "scn_workbooks_compass": "/Marketing/Screenshots/scn_workbooks_compass.png",
      "scn_journal_ai_wizard": "/Marketing/Screenshots/scn_journal_ai_wizard.webp",
      "scn_vitality_breath": "/Marketing/Screenshots/scn_vitality_breath.webp",
      "scn_tools_resentment_burner_02": "/Marketing/Screenshots/scn_tools_resentment_burner_02.webp",
      "scn_tools_main": "/Marketing/Screenshots/scn_tools_main.webp",
      "scn_tools_life_balance": "/Marketing/Screenshots/scn_tools_life_balance.webp",
      "scn_insights": "/Marketing/Screenshots/scn_insights.webp",
      "scn_dashboard_01_main": "/Marketing/Screenshots/scn_dashboard_01_main.png",
      "scn_feedback": "/Marketing/Screenshots/scn_feedback.webp",
      "scn_profile_data": "/Marketing/Screenshots/scn_profile_data.webp",
      "scn_dashboard_03_sos": "/Marketing/Screenshots/scn_dashboard_03_sos.webp",
      "scn_tools_abc_coping_tools": "/Marketing/Screenshots/scn_tools_abc_coping_tools.webp",
      "scn_urge_surfer": "/Marketing/Screenshots/scn_urge_surfer.webp",
      "scn_profile_03_security": "/Marketing/Screenshots/scn_profile_03_security.webp",
      "scn_tasks_log": "/Marketing/Screenshots/scn_tasks_log.webp",
      "scn_tools_resentment_burner_03": "/Marketing/Screenshots/scn_tools_resentment_burner_03.webp",
      "scn_journal_voice_record_01": "/Marketing/Screenshots/scn_journal_voice_record_01.webp",
      "scn_workbook_section_intro": "/Marketing/Screenshots/scn_workbook_section_intro.webp",
      "scn_tools_resentment_burner_01": "/Marketing/Screenshots/scn_tools_resentment_burner_01.webp",
      "scn_journal_voice_record_02": "/Marketing/Screenshots/scn_journal_voice_record_02.webp",
      "scn_tasks_this_week": "/Marketing/Screenshots/scn_tasks_this_week.webp",
      "scn_journal_write": "/Marketing/Screenshots/scn_journal_write.png",
      "scn_tools_cost_benefit_analysis": "/Marketing/Screenshots/scn_tools_cost_benefit_analysis.webp",
      "scn_workbooks": "/Marketing/Screenshots/scn_workbooks.webp",
      "scns_tools_dents": "/Marketing/Screenshots/scns_tools_dents.png",
      "scn_vitality_fuel": "/Marketing/Screenshots/scn_vitality_fuel.webp",
      "snc_tools_personalities": "/Marketing/Screenshots/snc_tools_personalities.png",
      "scn_profile_02_main": "/Marketing/Screenshots/scn_profile_02_main.webp"
    }
  }
} as const;

export type AssetPath = typeof ASSETS;
